### ISSUE TITLE
Can't push packages using tokens?

### ISSUE THREAD

**Issue by thequailman** [martinbaillie/vault-plugin-secrets-github#115]
For me, I can't push container images to ghcr.io using tokens from this secrets engine (full admin granted to the secrets engine in GitHub for the organization).  I'm pretty confident it's not a bug with the secrets engine, but something with how GitHub does authorization for apps, but I'm curious if anyone else has this issue.

**Comment by thequailman** [comment]
I think this is related to https://github.com/orgs/community/discussions/50180

**Comment by perillamint** [comment]
Also experiencing same issue with this. Granted `read:packages` and `write:packages` to the app, but the app token unable to push to the GHCR.

**Comment by martinbaillie** [comment]
Yeh folks these are GitHub app token limitations.
