### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by perbly** [martinbaillie/vault-plugin-secrets-github#117]
Hi

Thanks for this plugin. Works perfect.
But i can´t find the prometheus metrics mention in the readme and i can´t find references to it in the code.
We would like to use this metrics to see if the github is working properly.

```
Vault v1.15.1 (b94e275f25ccd9011146d14c00ea9e49fd5032dc), built 2023-10-20T19:16:11Z
vault_github_plugin_version: 2.0.0
```

Regards

**Comment by martinbaillie** [comment]
You'll find the metrics at `/v1/github/metrics` if you mounted it at `/github`
