### ISSUE TITLE
Support for roles?

### ISSUE THREAD

**Issue by grahamc** [martinbaillie/vault-plugin-secrets-github#14]
I think it'd be neat to be able to define a role which has predefined repositories and access levels defined in the role, as opposed to requiring the requester to specify them. Are you interested in that?

**Comment by martinbaillie** [comment]
For sure! That would be a great enhancement and shift the onus of responsibility to the pre-declared roles. Did you have an inclination on how best to achieve that with Vault's RBAC and plugin architecture? 🤔

**Comment by martinbaillie** [comment]
Available in https://github.com/martinbaillie/vault-plugin-secrets-github/releases/tag/v1.1.0
