### ISSUE TITLE
Maybe the app's private key shouldn't be readable

### ISSUE THREAD

**Issue by grahamc** [martinbaillie/vault-plugin-secrets-github#16]
I'm not sure, exactly, but I feel a bit weirded out that someone with root access on Vault can read back the private key from the config. What do you think? To me, it should operate like AWS's provider does, which does not return the secret key:

```
$ vault read aws/config/root
Key             Value
---             -----
access_key      AKIAxxxxxxxxxxxx
iam_endpoint    n/a
max_retries     -1
region          us-east-1
sts_endpoint    n/a
```

**Comment by martinbaillie** [comment]
Thanks @grahamc, I agree with this as a more secure default. It was an oversight on my part, being owner of GitHub and Vault in my current org I had access to both.

Users can always rewrite the key if they're not sure of the contents. No need for a read. I'll merge the PR and if anyone really needs the feature back I can always introduce an `exportable` flag to the config.

**Comment by grahamc** [comment]
Cool, thank you a lot!
