### ISSUE TITLE
Support revoking tokens

### ISSUE THREAD

**Issue by grahamc** [martinbaillie/vault-plugin-secrets-github#19]
I'm not sure what the exact code looks like just yet (but I can help write it :)) but revoking tokens isn't so far away. I think the return type from `client.go` would need to be structured a bit more, and define something like:

```
func (b *backend) pathSecrets() *framework.Secret {
        return &framework.Secret{
                Type: secretType,
                Fields: map[string]*framework.FieldSchema{
                        "api_key_token": {
                                Type:        framework.TypeString,
                                Description: "API token",
                        },
                },
                Revoke: b.operationRevoke,
        }
}
```

and then an `operationRevoke` function which does the delete you describe:

> I reckon a 
`curl  -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $token" -X DELETE https://api.github.com/installation/token` would keep you honest

_Originally posted by @martinbaillie in https://github.com/martinbaillie/vault-plugin-secrets-github/issues/17#issuecomment-759197261_

**Comment by martinbaillie** [comment]
Definitely! Having only recently learned you could revoke these tokens, this would be a nice enhancement to the plugin using the Vault lease API. Users can always call the GitHub endpoint directly as in the `curl` above but the lease API in Vault should allow you to revoke armed only with knowledge of the lease ID, not the token itself. 

Might take a quick gander at this now. Seems simple.

**Comment by martinbaillie** [comment]
@grahamc I've landed some miscellaneous changes in `master`, some of which introduces lease revocation using this GitHub endpoint. I haven't cut a release yet but please feel free to give it a try. Some details: https://github.com/martinbaillie/vault-plugin-secrets-github#revocation

**Comment by martinbaillie** [comment]
Revocation is in https://github.com/martinbaillie/vault-plugin-secrets-github/releases/tag/v1.1.0
