### ISSUE TITLE
Support multiple installations

### ISSUE THREAD

**Issue by grahamc** [martinbaillie/vault-plugin-secrets-github#20]
This would go nicely with #14, but I'm configuring the provider with multiple installations. To do that, I need to upload the private key multiple times. It might be interesting to make the installation ID part of a role definition or part of the write request itself to avoid mounting it multiple places.

**Comment by martinbaillie** [comment]
Yeh I see what you mean and how it would relate to #14. I'm not familiar enough with Vault RBAC internals at the moment to see if this sort of metadata (GitHub installation ID, default repo IDs + permissions etc.) can be carried with roles.
