### ISSUE TITLE
Support for additional API methods

### ISSUE THREAD

**Issue by dhess** [martinbaillie/vault-plugin-secrets-github#35]
Thanks very much for this plugin. We've been using it for a few weeks now for our CI, and it works wonderfully.

I'd like to use it for the [Terraform GitHub provider](https://registry.terraform.io/providers/integrations/github/latest/docs), as well, which requires an OAuth token or PAT, but many of the GitHub provider's resources require API permissions not covered by `vault-plugin-secrets-github` (basically, anything that doesn't operate on a repository).

Any plans for that?

**Comment by martinbaillie** [comment]
The plugin can support any permission the associated GitHub App can: https://docs.github.com/en/rest/reference/permissions-required-for-github-apps

Is that not what you’re after?

**Comment by dhess** [comment]
Perhaps I'm just confused.

We've been using the plugin's `/github/permissionset` endpoint, because we need to specify quite a few permissions on a relatively large number of repositories, which is a lot more convenient with permission sets than with the `/github/token` endpoint. I inferred from the [permission sets documentation](https://github.com/martinbaillie/vault-plugin-secrets-github#permission-sets) that the `repository_ids` parameter is required, but perhaps I'm misunderstanding.

How would one create a permission set that creates tokens which grant read+write access to, say, the [GitHub members API endpoints in `/orgs` and `/organizations`](https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-members)?

**Comment by martinbaillie** [comment]
Those parameters are optional. I'll make a note to improve the README in that area 👍🏻 

To do as you ask would look something like:
```shell
vault write /github/permissionset/demo-set permissions=members=write
vault read /github/token/demo-set
```

**Comment by dhess** [comment]
Thanks! I'll try that out and report back!

**Comment by dhess** [comment]
Yep, that works great! Thanks, and sorry for my confusion.
