### ISSUE TITLE
Alpine Target

### ISSUE THREAD

**Issue by jmls** [martinbaillie/vault-plugin-secrets-github#81]
Would it be possible to have alpine as a target for building ? We have a alpine version of vault and would like to use this plugin

**Comment by martinbaillie** [comment]
What makes an Alpine target different from the current Linux targets?

**Comment by jmls** [comment]
Absolutely nothing 😂

Sorry I have no idea what I was smoking when I created this ticket. My only
defence was that I was knackered

Sorry for the waste of bandwidth
